#!/bin/tcsh -f


iDSK newdisk.dsk -n

foreach file ( sphere hello incr )
        python ../utils/asc2pas.py -a ${file}.p -p ${file}.hsp -l
        iDSK newdisk.dsk -i ${file}.hsp -t 1
end

iDSK newdisk.dsk -l
